version: '3.8'

services:
  web:
    build: .
    container_name: ecom-test
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
    restart: always